### ISSUE TITLE
Support `doctor upload` for subformulas

### ISSUE THREAD

**Issue by krishna-vempati** [CloudElementsOpenLabs/the-doctor#12]
`doctor` does not seem to support upload of formulas that call subformulas. It would be great to extend the tool to support this, so we can fully leverage the power of subformulas.

**Comment by rrothenb** [comment]
It does under certain conditions. You have to make sure that the bundle of formulas it’s uploading contains all subformulas. 

It certainly should also support your case, but there is a workaround.
