### ISSUE TITLE
HOME missing in Windows environment

### ISSUE THREAD

**Issue by zleight1** [CloudElementsOpenLabs/the-doctor#4]
This tool doesn't work in windows because you reference `HOME` in the init script.

```
  const folderPath = `${process.env.HOME}/.doctor`
  const filePath = `${process.env.HOME}/.doctor/config.json`;
```

If you use `HOMEPATH` if `HOME` is undefined it will work.

**Comment by Jayme-T** [comment]
Wow thanks for noticing this- I just came to make the same ticket and assign it to myself and then saw it was made!
